dotnet-daycare/src/DayCare.WWW/Areas/Backoffice/Controllers/OrganisationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using DayCare.Db;
using DayCare.Models;
using DayCare.Models.Security;
using DayCare.Models.Utilities;
using DayCare.Models.ViewModels;

namespace DayCare.WWW.Areas.Backoffice.Controllers 
{
    [Area("Backoffice")]
    public class OrganisationController : BaseController 
    {
        public OrganisationController(ApplicationDbContext applicationDbContext):base(applicationDbContext)
        {
        }

        public async Task<IActionResult> Index() 
        {
            var model = await ApplicationDbContext.Organisations.OrderBy(o => o.Name).ToListAsync();

            if (this.Request.Headers["X-Requested-With"] == "XMLHttpRequest") 
            {
                return PartialView("_ListPartial", model);
            }
            
            return View(model);

        }

        [HttpGet]
        public IActionResult Create() 
        {
            var model = new Organisation();

            return View(model);
        } 

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Organisation model)
        {
            var alert = new Alert();
            try
            {
                if(!ModelState.IsValid) {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.INVALID;
                    throw new Exception();
                }
                    
                
                ApplicationDbContext.Organisations.Add(model);
                if (await ApplicationDbContext.SaveChangesAsync() == 0)
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.CREATENOK;
                    throw new Exception();
                }   

                alert.Message = ApplicationDbContextMessage.CREATEOK;
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                alert.Type = AlertType.Error;
                alert.ExceptionMessage = ex.Message;

                ModelState.AddModelError(string.Empty, alert.ExceptionMessage);
            }
            return View(model);
        }
        
        [HttpGet]
        public async Task<IActionResult> Edit(Int16? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(400);
            }
            
            var model = await ApplicationDbContext.Organisations.FirstOrDefaultAsync(m => m.Id == id);
            
            if(model == null)
            {
                return RedirectToAction("Index");
            }
            
            return View(model);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Organisation model)
        {
            var alert = new Alert();
            try 
            {
                if(!ModelState.IsValid)
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.INVALID;
                    throw new Exception();
                }   
                    
                var originalModel = ApplicationDbContext.Organisations.FirstOrDefault(m => m.Id == model.Id);
                
                if(originalModel == null) 
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.NOTEXISTS;
                    throw new Exception();
                }
                    
                originalModel.Name = model.Name;
                originalModel.Description = model.Description;
                
                ApplicationDbContext.Organisations.Attach(originalModel);
                ApplicationDbContext.Entry(originalModel).State = EntityState.Modified;
                
                if (await ApplicationDbContext.SaveChangesAsync() == 0)
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.EDITNOK;
                    throw new Exception();
                } 
                
                alert.Message = ApplicationDbContextMessage.EDITOK;
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                alert.Type = AlertType.Error;
                alert.ExceptionMessage = ex.Message;

                ModelState.AddModelError(string.Empty, alert.ExceptionMessage);
            }
            return View(model);
        }

        [HttpGet("[area]/[controller]/[action]/{id:int}")]
        public async Task<IActionResult> Delete(Int16 id, [FromQuery] ActionType actionType)
        {
            var model = await ApplicationDbContext.Organisations.FirstOrDefaultAsync(m => m.Id == id);
            
            if(model == null)
            {
                return RedirectToAction("Index");
            }
            
            var viewModel = new ActionOrganisationViewModel()
            {
                BaseEntity = model,
                ActionType = actionType
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(ActionOrganisationViewModel model)
        {
            var alert = new Alert();// Alert
            try
            {
                var originalModel = ApplicationDbContext.Organisations.FirstOrDefault(m => m.Id == model.BaseEntity.Id);
                
                if(originalModel == null)
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.NOTEXISTS;
                    throw new Exception();
                }

                switch(model.ActionType)
                {
                    case ActionType.Delete:
                        alert.Message = ApplicationDbContextMessage.DELETEOK;
                        ApplicationDbContext.Entry(originalModel).State = EntityState.Deleted;
                        break;
                    case ActionType.SoftDelete:
                        alert.Message = ApplicationDbContextMessage.SOFTDELETEOK;
                        originalModel.DeletedAt = DateTime.Now;
                        ApplicationDbContext.Entry(originalModel).State = EntityState.Modified;
                        break;
                    case ActionType.SoftUnDelete:
                        alert.Message = ApplicationDbContextMessage.SOFTUNDELETEOK;
                        originalModel.DeletedAt = (Nullable<DateTime>)null;
                        ApplicationDbContext.Entry(originalModel).State = EntityState.Modified;
                        break;
                }

                
                if (await ApplicationDbContext.SaveChangesAsync() == 0)
                {                   
                    switch(model.ActionType)
                    {
                        case ActionType.Delete:
                            alert.Message = ApplicationDbContextMessage.DELETENOK;
                            break;
                        case ActionType.SoftDelete:
                            alert.Message = ApplicationDbContextMessage.SOFTDELETENOK;
                            break;
                        case ActionType.SoftUnDelete:
                            alert.Message = ApplicationDbContextMessage.SOFTUNDELETENOK;
                            break;
                    }
                    throw new Exception();
                } 

                if (this.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    return Json(alert);
                }
                else
                {
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                alert.Type = AlertType.Error;
                alert.ExceptionMessage = ex.Message;

                if (this.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    return Json(alert);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
        }
    }
}

dotnet-daycare/src/DayCare.WWW/Areas/Backoffice/Views/Organisation/Create.cshtml
@model DayCare.Models.Organisation
@{
    ViewBag.Title = "Organisation Management";
    ViewBag.SubTitle = "Manage all your groups via this platform";
    ViewBag.Description = "Create an organisation via the form or got back to the list of organisations ...";
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}
<div class="mdl-cell mdl-cell--3-col mdl-cell--12-col-tablet mdl-cell--12-col-phone mdl-color--grey-100">
    @Html.Partial("_QuickActionsPartial")
</div>
<div class="mdl-cell mdl-cell--9-col mdl-cell--12-col-tablet mdl-cell--12-col-phone no-p-l">
    <div class="ahs-card-holder ahs-card-holder--first">
        <div class="mdl-card mdl-shadow--1dp ahs-card">
          <div class="mdl-card__title">
            <h2 class="mdl-card__title-text">Create a new organisation</h2>
          </div>
          <div class="form-holder">
            <form asp-controller="Organisation" asp-action="Create" method="post" asp-antiforgery="true">
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label ahs-textfield--block">
                    <input class="mdl-textfield__input" asp-for="Name">
                    <label class="mdl-textfield__label" asp-for="Name">Name</label>
                    <span class="mdl-textfield__error" asp-for="Name" ></span>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label ahs-textfield--block">
                    <input class="mdl-textfield__input" asp-for="Description">
                    <label class="mdl-textfield__label" asp-for="Description">Description</label>
                    <span class="mdl-textfield__error" asp-for="Description"></span>
                </div>
                <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">Save</button>
            </form>
          </div>
        </div>
    </div>
</div>

dotnet-daycare/src/DayCare.WWW/Areas/Backoffice/Views/Organisation/Delete.cshtml
@model DayCare.Models.ViewModels.ActionOrganisationViewModel
@{
    ViewBag.Title = "Organisation Management";
    ViewBag.SubTitle = "Manage all the organisations on your SAAS platform";
    ViewBag.Description = "Create an organisation via the form or go back to the list of organisations.";
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}
<div class="mdl-cell mdl-cell--3-col mdl-cell--12-col-tablet mdl-cell--12-col-phone mdl-color--grey-100">
    @Html.Partial("_QuickActionsPartial")
</div>
<div class="mdl-cell mdl-cell--9-col mdl-cell--12-col-tablet mdl-cell--12-col-phone no-p-l">
    <div class="ahs-card-holder ahs-card-holder--first">
        <div class="mdl-card mdl-shadow--1dp ahs-card">
          <div class="mdl-card__title">
            <h2 class="mdl-card__title-text">
                @Model.Action an existing organisation</text>
            </h2>
          </div>
          <div class="form-holder">
            <p>Do you wish to @Model.Action the organisation @Model.BaseEntity.Name?</p>
            <form asp-controller="Organisation" asp-action="Delete" method="post" asp-antiforgery="true">
                <input asp-for="BaseEntity.Id" type="hidden">
                <input asp-for="BaseEntity.Name" type="hidden">
                <input asp-for="BaseEntity.Description" type="hidden">
                <input asp-for="ActionType" type="hidden">
                <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">@Model.Action</button>
            </form>
          </div>
        </div>
    </div>
</div>

dotnet-daycare/src/DayCare.WWW/Areas/Backoffice/Views/Organisation/Edit.cshtml
@model DayCare.Models.Organisation
@{
    ViewBag.Title = "Organisation Management";
    ViewBag.SubTitle = "Manage all the organisations on your SAAS platform";
    ViewBag.Description = "Edit an existing organisation via the form or go back to the list of organisations.";
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}
<div class="mdl-cell mdl-cell--3-col mdl-cell--12-col-tablet mdl-cell--12-col-phone mdl-color--grey-100">
    @Html.Partial("_QuickActionsPartial")
</div>
<div class="mdl-cell mdl-cell--9-col mdl-cell--12-col-tablet mdl-cell--12-col-phone no-p-l">
    <div class="ahs-card-holder ahs-card-holder--first">
        <div class="mdl-card mdl-shadow--1dp ahs-card">
          <div class="mdl-card__title">
            <h2 class="mdl-card__title-text">Edit an exisiting organisation</h2>
          </div>
          <div class="form-holder">
            <form asp-controller="Organisation" asp-action="Edit" method="post" asp-antiforgery="true">
                <input asp-for="Id" type="hidden">
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label ahs-textfield--block">
                    <input class="mdl-textfield__input" asp-for="Name">
                    <label class="mdl-textfield__label" asp-for="Name">Name</label>
                    <span class="mdl-textfield__error" asp-for="Name" ></span>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label ahs-textfield--block">
                    <input class="mdl-textfield__input" asp-for="Description">
                    <label class="mdl-textfield__label" asp-for="Description">Description</label>
                    <span class="mdl-textfield__error" asp-for="Description"></span>
                </div>
                <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">Update</button>
            </form>
          </div>
        </div>
    </div>
</div>

dotnet-daycare/src/DayCare.WWW/Areas/Backoffice/Views/Organisation/Index.cshtml
@model ICollection<DayCare.Models.Organisation>
@{
    ViewBag.Title = "Organisation Management";
    ViewBag.SubTitle = "Manage all your organisations via this platform";
    ViewBag.Description = "Select an organisation to edit ...";
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}
<div class="mdl-cell mdl-cell--3-col mdl-cell--12-col-tablet mdl-cell--12-col-phone mdl-color--grey-100">
    @Html.Partial("_QuickActionsPartial")
</div>
<div class="mdl-cell mdl-cell--9-col mdl-cell--12-col-tablet mdl-cell--12-col-phone no-p-l">
    <div class="ahs-card-holder ahs-card-holder--first">
        <div class="mdl-card mdl-shadow--1dp ahs-card">
          <div class="mdl-card__title">
            <h2 class="mdl-card__title-text">Organisation listing</h2>
          </div>
          @Html.Partial("_ListPartial", @Model)
        </div>
    </div>
</div>

dotnet-daycare/src/DayCare.WWW/Areas/Backoffice/Views/Organisation/_ListPartial.cshtml
@model ICollection<DayCare.Models.Organisation>
@Html.AntiForgeryToken()
@if (Model != null && Model.Count() > 0)
{
      <table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable is-upgraded ahs-table" data-upgraded=",MaterialDataTable">
        <colgroup>
          <col class="auto-cell-size p-r-20">
        </colgroup>
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Created</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          @foreach (var organisation in Model)
          {
            <tr data-id="organisation-@organisation.Id">
              <td>@organisation.Name</td>
              <td>@organisation.Description</td>
              <td>@organisation.CreatedAt</td>
              <td>
                <a asp-controller="Organisation" asp-action="Edit" asp-route-id="@organisation.Id">
                  <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">edit</i>
                </a>
                @if (@organisation.DeletedAt != null)
                {
                    <a asp-controller="Organisation" asp-action="Delete" asp-route-id="@organisation.Id" asp-route-actionType="5" data-is-softdelete="true">
                      <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">delete</i>
                    </a>
                }
                else
                {
                    <a asp-controller="Organisation" asp-action="Delete" asp-route-id="@organisation.Id" asp-route-actionType="4">
                      <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">delete</i>
                    </a>
                }
                <a asp-controller="Organisation" asp-action="Delete" asp-route-id="@organisation.Id" asp-route-actionType="3">
                  <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">delete_forever</i>
                </a>
              </td>
            </tr>
          }
        </tbody>
      </table>
}
else
{
    <p>No Organisations in the database!</p>
}
</div>

dotnet-daycare/src/DayCare.WWW/Areas/Backoffice/Views/Organisation/_QuickActionsPartial.cshtml
<div class="ahs-list-overview">
    <div class=" mdl-color-text--blue-grey-400">
        <h3><i class=" material-icons f-left m-r-5">dvr</i> Overview</h3>
        <p>@ViewBag.Description</p>
        <ul class="ahs-list-overview__list">
            <li><a asp-controller="Organisation" asp-action="Index"><i class="material-icons">list</i>List of items</a></li>
            <li><a asp-controller="Organisation" asp-action="Create"><i class="material-icons">add</i>Create a new item</a></li>
            <li><a href=""><i class="material-icons">file_download</i>Export items</a></li>
        </ul>
    </div>
</div>